production:
  adapter: postgresql
  host: ""
  database: tarot_api_production
  username: postgres
  password:
  encoding: unicode
  pool: 5

development:
  host: localhost
  port: 5432
  adapter: postgresql
  database: tarot_api_dev
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

test:
  host: localhost
  port: 5432
  adapter: postgresql
  database: tarot_api_test
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>